import { Product } from '../types';
import { generateBarcode } from './barcodeUtils';
import { Sale, Location } from '../types';

export function generateMockLocations(): Location[] {
  return [
    {
      id: 'loc-001',
      name: 'Main Warehouse',
      type: 'warehouse',
      address: '1234 Industrial Blvd',
      city: 'Fashion City',
      state: 'CA',
      zipCode: '90210',
      phone: '(555) 123-4567',
      manager: 'John Warehouse',
      capacity: 10000,
      isActive: true,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'loc-002',
      name: 'Downtown Store',
      type: 'store',
      address: '456 Fashion Ave',
      city: 'Fashion City',
      state: 'CA',
      zipCode: '90211',
      phone: '(555) 234-5678',
      manager: 'Sarah Store',
      capacity: 500,
      isActive: true,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'loc-003',
      name: 'Mall Store',
      type: 'store',
      address: '789 Shopping Mall',
      city: 'Fashion City',
      state: 'CA',
      zipCode: '90212',
      phone: '(555) 345-6789',
      manager: 'Mike Mall',
      capacity: 300,
      isActive: true,
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'loc-004',
      name: 'North Warehouse',
      type: 'warehouse',
      address: '321 Storage St',
      city: 'North City',
      state: 'CA',
      zipCode: '90213',
      phone: '(555) 456-7890',
      manager: 'Lisa North',
      capacity: 8000,
      isActive: true,
      createdAt: new Date('2024-01-01'),
    },
  ];
}

export function generateMockData(): Product[] {
  const locations = generateMockLocations();
  
  const products = [
    {
      id: '1',
      name: 'Classic Cotton T-Shirt',
      category: 'shirts',
      size: 'M',
      color: 'White',
      price: 24.99,
      cost: 12.50,
      wholesalePrice: 19.99,
      price: 1999,
      cost: 1000,
      wholesalePrice: 1599,
      wholesaleMinQuantity: 100,
      stock: 45,
      minStock: 10,
      sku: 'TSH-WHT-M-001',
      description: 'Comfortable 100% cotton t-shirt perfect for everyday wear',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
      locationId: 'loc-001',
      location: locations[0],
      imageUrls: [
        'https://images.pexels.com/photos/1020585/pexels-photo-1020585.jpeg?auto=compress&cs=tinysrgb&w=400',
        'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
    },
    {
      id: '2',
      name: 'Slim Fit Jeans',
      category: 'pants',
      size: '32',
      color: 'Dark Blue',
      price: 79.99,
      cost: 35.00,
      wholesalePrice: 65.99,
      price: 6399,
      cost: 2800,
      wholesalePrice: 5279,
      wholesaleMinQuantity: 100,
      stock: 8,
      minStock: 15,
      sku: 'JNS-BLU-32-002',
      description: 'Modern slim fit jeans with premium denim',
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-01-20'),
      locationId: 'loc-002',
      location: locations[1],
      imageUrls: [
        'https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?auto=compress&cs=tinysrgb&w=400',
        'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
    },
    {
      id: '3',
      name: 'Summer Floral Dress',
      category: 'dresses',
      size: 'S',
      color: 'Floral Print',
      price: 89.99,
      cost: 42.00,
      wholesalePrice: 74.99,
      price: 7199,
      cost: 3360,
      wholesalePrice: 5999,
      wholesaleMinQuantity: 100,
      stock: 22,
      minStock: 8,
      sku: 'DRS-FLR-S-003',
      description: 'Light and breezy summer dress with beautiful floral pattern',
      createdAt: new Date('2024-01-25'),
      updatedAt: new Date('2024-01-25'),
      locationId: 'loc-003',
      location: locations[2],
      imageUrls: [
        'https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
    },
    {
      id: '4',
      name: 'Leather Bomber Jacket',
      category: 'jackets',
      size: 'L',
      color: 'Black',
      price: 159.99,
      cost: 80.00,
      wholesalePrice: 129.99,
      price: 12799,
      cost: 6400,
      wholesalePrice: 10399,
      wholesaleMinQuantity: 100,
      stock: 12,
      minStock: 5,
      sku: 'JKT-BLK-L-004',
      description: 'Premium leather bomber jacket with modern cut',
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-02-01'),
      locationId: 'loc-001',
      location: locations[0],
      imageUrls: [
        'https://images.pexels.com/photos/1124468/pexels-photo-1124468.jpeg?auto=compress&cs=tinysrgb&w=400',
        'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=400',
        'https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
    },
    {
      id: '5',
      name: 'Running Sneakers',
      category: 'shoes',
      size: '9',
      color: 'Gray/Blue',
      price: 129.99,
      cost: 65.00,
      wholesalePrice: 109.99,
      price: 10399,
      cost: 5200,
      wholesalePrice: 8799,
      wholesaleMinQuantity: 100,
      stock: 18,
      minStock: 12,
      sku: 'SHO-GRY-9-005',
      description: 'High-performance running shoes with advanced cushioning',
      createdAt: new Date('2024-02-05'),
      updatedAt: new Date('2024-02-05'),
      locationId: 'loc-004',
      location: locations[3],
      imageUrls: [
        'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
    },
    {
      id: '6',
      name: 'Silk Scarf',
      category: 'accessories',
      size: 'One Size',
      color: 'Red',
      price: 45.99,
      cost: 18.00,
      wholesalePrice: 36.99,
      price: 3679,
      cost: 1440,
      wholesalePrice: 2959,
      wholesaleMinQuantity: 100,
      stock: 6,
      minStock: 20,
      sku: 'ACC-RED-OS-006',
      description: 'Elegant silk scarf perfect for any occasion',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-10'),
      locationId: 'loc-002',
      location: locations[1],
      imageUrls: [
        'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress&cs=tinysrgb&w=400',
        'https://images.pexels.com/photos/1020585/pexels-photo-1020585.jpeg?auto=compress&cs=tinysrgb&w=400'
      ],
    },
  ];

  // Add barcodes to all products
  return products.map(product => ({
    ...product,
    barcode: generateBarcode(product.id, product.category)
  }));
}

export function generateId(): string {
  return Math.random().toString(36).substr(2, 9);
}

export function generateMockSales(): Sale[] {
  const mockSales: Sale[] = [
    {
      id: generateId(),
      items: [
        {
          productId: '1',
          product: {
            id: '1',
            name: 'Classic Cotton T-Shirt',
            category: 'shirts',
            size: 'M',
            color: 'White',
            price: 24.99,
            cost: 12.50,
            wholesalePrice: 19.99,
            wholesaleMinQuantity: 100,
            stock: 45,
            minStock: 10,
            sku: 'TSH-WHT-M-001',
            createdAt: new Date('2024-01-15'),
            updatedAt: new Date('2024-01-15'),
          },
          quantity: 2,
          price: 24.99,
          total: 49.98,
        },
      ],
      subtotal: 49.98,
      tax: 4.00,
      total: 53.98,
      paymentMethod: 'card',
      customerName: 'John Smith',
      soldBy: 'Sales Representative',
      soldById: '2',
      createdAt: new Date('2024-01-22T10:30:00'),
    },
    {
      id: generateId(),
      items: [
        {
          productId: '2',
          product: {
            id: '2',
            name: 'Slim Fit Jeans',
            category: 'pants',
            size: '32',
            color: 'Dark Blue',
            price: 79.99,
            cost: 35.00,
            wholesalePrice: 65.99,
            wholesaleMinQuantity: 100,
            stock: 8,
            minStock: 15,
            sku: 'JNS-BLU-32-002',
            createdAt: new Date('2024-01-20'),
            updatedAt: new Date('2024-01-20'),
          },
          quantity: 1,
          price: 79.99,
          total: 79.99,
        },
      ],
      subtotal: 79.99,
      tax: 6.40,
      total: 86.39,
      paymentMethod: 'cash',
      customerName: 'Sarah Johnson',
      soldBy: 'Admin User',
      soldById: '1',
      createdAt: new Date('2024-01-22T14:15:00'),
    },
    {
      id: generateId(),
      items: [
        {
          productId: '3',
          product: {
            id: '3',
            name: 'Summer Floral Dress',
            category: 'dresses',
            size: 'S',
            color: 'Floral Print',
            price: 89.99,
            cost: 42.00,
            wholesalePrice: 74.99,
            wholesaleMinQuantity: 100,
            stock: 22,
            minStock: 8,
            sku: 'DRS-FLR-S-003',
            createdAt: new Date('2024-01-25'),
            updatedAt: new Date('2024-01-25'),
          },
          quantity: 1,
          price: 89.99,
          total: 89.99,
        },
        {
          productId: '6',
          product: {
            id: '6',
            name: 'Silk Scarf',
            category: 'accessories',
            size: 'One Size',
            color: 'Red',
            price: 45.99,
            cost: 18.00,
            wholesalePrice: 36.99,
            wholesaleMinQuantity: 100,
            stock: 6,
            minStock: 20,
            sku: 'ACC-RED-OS-006',
            createdAt: new Date('2024-02-10'),
            updatedAt: new Date('2024-02-10'),
          },
          quantity: 2,
          price: 45.99,
          total: 91.98,
        },
      ],
      subtotal: 181.97,
      tax: 14.56,
      total: 196.53,
      paymentMethod: 'card',
      customerName: 'Emily Davis',
      soldBy: 'Sales Representative',
      soldById: '2',
      createdAt: new Date('2024-01-23T09:45:00'),
    },
  ];

  return mockSales;
}